# Generated by Django 4.1.5 on 2023-01-17 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_alter_comment_parent'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='comments.comment', verbose_name='comment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_like_owner', to=settings.AUTH_USER_MODEL, verbose_name='comment_like_owner')),
            ],
            options={
                'verbose_name': 'comment like',
                'verbose_name_plural': 'Comment likes',
            },
        ),
    ]
