# Generated by Django 4.1.5 on 2023-01-17 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 6, 39, 50, 763461, tzinfo=datetime.timezone.utc), verbose_name='last_activity'),
        ),
    ]
