# Generated by Django 4.1.5 on 2023-01-17 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 6, 42, 26, 754909, tzinfo=datetime.timezone.utc), verbose_name='last_activity'),
        ),
    ]
