# Generated by Django 4.1.5 on 2023-01-20 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 8, 8, 57, 471208, tzinfo=datetime.timezone.utc), verbose_name='last_activity'),
        ),
    ]
